### ISSUE TITLE
Video Prediction

### ISSUE THREAD

**Issue by M-Colley** [Smail8/Pedestrian-Intention-Prediction-A-Muti-Task-Perspective#2]
Hey, thanks for sharing your work!

Would it be possible to implement the prediction and visualizing it in videos?
Are there any intentions to provide such functionality or some hints how to do this? 

Kind regards!

**Comment by Smail8** [comment]
Hi there,

 Thank you for your interest in our research. This repository is not maintained. Please refer to the official [repository ](https://github.com/vita-epfl/bounding-box-prediction )for the correct code as well as the trained model. Also if you have other issues please post them on that repo.

It is hard to visualize in an understandable manner bounding box predictions as well as intentions for each frame, we have tried and it is just not understandable. For that reason, we are not currently working on a visualization tool in videos.
Please do not hesitate to ask any other questions on the official repo. I will be deleting this one soon.

**Comment by M-Colley** [comment]
Thank you very much!
